App/Areas/Public/Controllers/ProductoPublicController.cs
using System;
using System.Threading.Tasks;

using App.Areas.Administrador.Services;
using App.Utils;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace App.Areas.Public.Controllers
{
	[Area("Public")]
	public class ProductoPublicController : Controller
	{
		private readonly IConfiguration _configuration;
		private readonly IImagenService _imagenService;
		private readonly IProductoService _productoService;

		public ProductoPublicController(IConfiguration configuration,
			IImagenService imagenService, IProductoService productoService)
		{
			_configuration = configuration;
			_imagenService = imagenService;
			_productoService = productoService;
		}

		// GET: Public/Producto/Details/5
		[HttpGet("producto-detail/{id:long}")]
		public async Task<IActionResult> Details(long id)
		{
			var producto = await _productoService.GetById(id);
			var imagenes = await _imagenService.GetListByIdAsync(producto.Id);
			if (imagenes != null)
			{
				producto.Imagenes = imagenes;
			}

			var descuentoSol = (double) producto.PrecioNormal -
			                   (double) producto.DescuentoPrecio * (double) producto.PrecioNormal;
			var descuentoUsd = (double) producto.PrecioNormal / Currency.Dolar -
			                   (double) producto.DescuentoPrecio * ((double) producto.PrecioNormal / Currency.Dolar);
			ViewBag.PrecioNormalSol = Math.Round(producto.PrecioNormal, 2);
			ViewBag.PrecioNormalUSD = Math.Round((double) producto.PrecioNormal / Currency.Dolar, 2);

			ViewBag.DescuentoPrecioSol = Math.Round(descuentoSol, 2);
			ViewBag.PriceProductPaypal = Math.Round(descuentoUsd, 2);

			producto.DescuentoPrecio *= 100;
			return View(producto);
		}

		[Authorize]
		[Route("pagar/{id:long}")]
		public async Task<IActionResult> Payed(long id)
		{
			var producto = await _productoService.GetById(id);
			ViewBag.ClientId = _configuration["ClientId"];
			var descuentoUsd = (double) producto.PrecioNormal / Currency.Dolar -
			                   (double) producto.DescuentoPrecio * ((double) producto.PrecioNormal / Currency.Dolar);
			ViewBag.PriceProductPaypal = Math.Round(descuentoUsd, 2);
			var imagenes = await _imagenService.GetListByIdAsync(producto.Id);
			if (imagenes != null)
			{
				producto.Imagenes = imagenes;
			}

			producto.DescuentoPrecio *= 100;

			return View(producto);
		}
	}
}

App/Areas/Public/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using App.Areas.Administrador.Services;
using App.Areas.Public.Services;

using Domain.Models;

using Microsoft.AspNetCore.Mvc;

namespace App.Areas.Public.Controllers
{
	[Area("Public")]
	[Route("tienda")]
	public class TiendaController : Controller
	{
		private readonly ICategoriaService _categoria;
		private readonly IProductoService _producto;

		public TiendaController(ICategoriaService categoria, IProductoService producto)
		{
			_categoria = categoria;
			_producto = producto;
		}

		[HttpGet("by/categoria")]
		public async Task<IActionResult> ProductosByCategoria([FromQuery(Name = "categoria")] string nombre)
		{
			ViewBag.Categorias = await _categoria.GetAll();
			if (string.IsNullOrEmpty(nombre))
			{
				return View(await _producto.GetAll(15));
			}

			ICollection<Productos> filterData;

			var categoria = await _categoria.GetByNombre(nombre);
			ViewBag.NombreCategoria = categoria.Nombre;
			filterData = await _categoria.GetProductosByCategoriaId(categoria.Id);

			return View(filterData);
		}
	}
}

App/Areas/Public/Views/Tienda/Index.cshtml
@{
	ViewData["Title"] = "Tienda";
	Layout = "_Layout";
}

<div class="row">
	<div class='col col-sm-3 col-md-3'>
		<h4 class="color-content">Categorias</h4>
		<ul class="list-group">
			@foreach (var item in ViewBag.Categorias)
			{
				<li class="list-group-item">
					<input class="form-check-input me-1" type="checkbox" value="@item.Nombre" aria-label="@item.Nombre">
					@item.Nombre
				</li>
			}
		</ul>
	</div>
	<div class='col col-sm-9 col-md-9'>
		<h4 class="color-primary text-center">Todos los Productos</h4>
		<div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
			@foreach (var item in Model)
			{
				<div class="card mx-2" style="width: 18rem;">
					@if (item.Imagenes != null)
					{
						<img src="@item.Imagenes.FirstOrDefault()?.NombreImagen" class="card-img-top" alt="...">
					}
					else
					{
						<img src="@item.ImagenPrincipal" class="card-img-top" alt="@item.Nombre">
					}
					<div class="card-body d-flex flex-column justify-content-center">
						<h5 class="card-title">@item.Nombre</h5>
						<p class="color-primary">Categoria: <b>@ViewBag.NombreCategoria</b></p>
						<p class="card-text">@item.Descripcion</p>
						<a asp-action="Details" asp-controller="ProductoPublic" asp-route-id="@item.Id" class="btn btn-primary">Comprar</a>
					</div>
				</div>
			}
		</div>
	</div>

</div>

App/Areas/Public/Views/Tienda/ProductosByCategoria.cshtml
@model ICollection<Domain.Models.Productos>
@{
	Layout = "_Layout";
	ViewData["Title"] = "Productos por Categoría";
}
<hr class="color-primary">
<div class='container my-5'>
	<div class="row">
		<div class='col col-sm-3 col-md-3'>
			<h2 class="color-content my-3">Categorias</h2>
			<ul class="list-group">
				@foreach (var item in ViewBag.Categorias)
				{
					<li class="list-group-item">
						<input class="form-check-input me-1" type="checkbox" value="@item.Nombre" aria-label="@item.Nombre">
						@item.Nombre
					</li>
				}
			</ul>
		</div>
		<div class='col col-sm-9 col-md-9'>
			<h2 class="color-primary text-center my-3">Todos los Productos</h2>
			<div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
				@foreach (var item in Model)
				{
					<div class="card mx-2 py-2" style="width: 18rem;">
						<img src="@item.ImagenPrincipal" class="card-img-top" alt="@item.Nombre">
						<div class="card-body d-flex flex-column justify-content-center">
							<h5 class="card-title color-primary">@item.Nombre</h5>
							<p class="color-primary">Categoria: <b>@ViewBag.NombreCategoria</b></p>
							<p class="card-text color-content">@item.Descripcion</p>
							<a asp-action="Details" asp-controller="ProductoPublic" asp-route-id="@item.Id" class="btn btn-primary">Comprar</a>
						</div>
					</div>
				}
			</div>
		</div>
	</div>
</div>

@section Scripts
{
	<script type=text/javascript>
		 let list = [];
		 let listFiltersDOM = document.querySelectorAll('.form-check-input.me-1');
		 listFiltersDOM.forEach(item => {
			 item.addEventListener('change', evt => {
				 let value = evt.target.value;
				 if (!(list.indexOf(value) > -1) && evt.target.checked){
					 list.push(value);
				 } else {
					 list.filter(v => v !== value);
				 }
			 window.location.search = `categoria=${list.join(',')}`;
			 });
		 });
		 
		 function send() {
		 }
	</script>
}