App/Areas/Public/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using App.Areas.Administrador.Services;
using App.Areas.Public.Services;

using Domain.Models;

using Microsoft.AspNetCore.Mvc;

namespace App.Areas.Public.Controllers
{
	[Area("Public")]
	[Route("tienda")]
	public class TiendaController : Controller
	{
		private readonly ICategoriaService _categoria;
		private readonly IProductoService _producto;

		public TiendaController(ICategoriaService categoria, IProductoService producto)
		{
			_categoria = categoria;
			_producto = producto;
		}

		[HttpGet("by/categoria")]
		public async Task<IActionResult> ProductosByCategoria([FromQuery(Name = "categoria")] string nombre)
		{
			ViewBag.Categorias = await _categoria.GetAll();
			if (string.IsNullOrEmpty(nombre))
			{
				return View(await _producto.GetAll(15));
			}

			ICollection<Productos> filterData;

			var categoria = await _categoria.GetByNombre(nombre);
			ViewBag.NombreCategoria = categoria.Nombre;
			filterData = await _categoria.GetProductosByCategoriaId(categoria.Id);

			return View(filterData);
		}
	}
}

App/Areas/Public/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang=es>

<head>
	<meta charset=utf-8/>
	<meta name=viewport content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"]	| Ecopeque</title>
	<link rel=stylesheet href=~/lib/bootstrap/dist/css/bootstrap.css>
	<link rel=stylesheet href=~/css/site.css/>
	<link rel='icon' type="image/png" sizes="50x50" href='~/logo-ecopeque.png'>
</head>

<body>
<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container container-fluid">
			<a class="navbar-brand color-primary" asp-area=Public asp-controller=Home asp-action=Index>Ecopeque</a>
			<button class=navbar-toggler type=button data-bs-toggle=collapse data-bs-target=#navbarNavEcommerce
			        aria-controls=navbarNavEcommerce aria-expanded=false aria-label="Toggle navigation">
				<span class=navbar-toggler-icon></span>
			</button>
			<div class="collapse navbar-collapse" id=navbarNavEcommerce>
				<ul class=navbar-nav>
					<li class=nav-item>
						<a class="nav-link active color-primary" aria-current=page asp-area=Public asp-controller=Home asp-action=Index>Inicio</a>
					</li>
					<li class=nav-item>
						<a class=nav-link asp-controller="Tienda" asp-action="Index">Tienda</a>
					</li>
					<li class=nav-item>
						<a class=nav-link href=#>Sobre Nostros</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href=# id=navbarDropdownMenuLinkEcommerce role=button
						   data-bs-toggle=dropdown aria-expanded=false>
							Categorias
						</a>
						<ul class=dropdown-menu aria-labelledby=navbarDropdownMenuLinkEcommerce>
							<li>
								<a class=dropdown-item asp-controller="Tienda" asp-action="ProductosByCategoria">Productos por categorias</a>
							</li>
						</ul>
					</li>
					<li class="nav-item d-flex flex-grow-1">
						<span class="flex-grow-1"></span>
					</li>
					<li class="nav-item">
						@{
							System.Diagnostics.Debug.Assert(User.Identity != null, "User.Identity != null");
						}
						@if (User.Identity.IsAuthenticated)
						{
							<div class="d-flex flex-sm-column flex-md-row justify-content-md-between align-items-md-center">
								<p class="text-success">@User.Identity.Name</p>
								<form asp-area=Cliente asp-controller=Cuenta asp-action=Logout>
									<button type="submit" class="btn btn-secondary">
										Cerrar sesión
									</button>
								</form>
							</div>
						}
						else
						{
							<a class=nav-link asp-area=Cliente asp-controller=Cuenta asp-action=Login>Iniciar Sesión</a>
						}
					</li>
				</ul>
			</div>
		</div>
	</nav>
</header>
<main role=main class="pb-3 container-fluid">
	@RenderBody()
</main>

<footer class="border-top footer text-muted">
	<div class=container>
		&copy; 2021 - Ecommerce
	</div>
</footer>
<persist-component-state/>
<script src=~/lib/bootstrap/dist/js/bootstrap.bundle.min.js></script>
<script src=~/js/site.js asp-append-version=true></script>
<script src=_framework/blazor.server.js></script>
@await RenderSectionAsync("Scripts", false)
</body>

</html>